version: '3'
services:
  task-management-db:
    image: postgres:13.4-alpine
    container_name: task-management-databse
    environment:
      POSTGRES_USER: task-management
      POSTGRES_PASSWORD: task-management
      POSTGRES_DB: task_management
    ports:
      - '15432:5432'
    volumes:
      - ./database/lib/data:/var/lib/postgresql/data
